In [1]:
import tensorflow as tf

In [2]:
import numpy as np

In [3]:
print(tf.__version__)

1.3.0


In [4]:
from tensorflow.contrib.learn.python.learn.datasets import base
import os
import urllib


In [6]:
IRIS_TRAINING = "iris_training.csv"
IRIS_TRAINING_URL = "http://download.tensorflow.org/data/iris_training.csv"

IRIS_TEST = "iris_test.csv"
IRIS_TEST_URL = "http://download.tensorflow.org/data/iris_test.csv"

if not os.path.exists(IRIS_TRAINING):
    local_filename, headers = urllib.request.urlretrieve(IRIS_TRAINING_URL)
    with open(IRIS_TRAINING, "w") as f:
        f.write(open(local_filename).read())

if not os.path.exists(IRIS_TEST):
    test_filename, headers = urllib.request.urlretrieve(IRIS_TEST_URL)
    with open(IRIS_TRAINING, "w") as f:
        f.write(open(test_filename).read())

training_set = base.load_csv_with_header(filename=IRIS_TRAINING, 
                                          features_dtype=np.float32,
                                          target_dtype=np.int)

test_set = base.load_csv_with_header(filename=IRIS_TEST,
                                     features_dtype=np.float32,
                                     target_dtype=np.int
                                    )

print(training_set.data)

[[ 5.9000001   3.          4.19999981  1.5       ]
 [ 6.9000001   3.0999999   5.4000001   2.0999999 ]
 [ 5.0999999   3.29999995  1.70000005  0.5       ]
 [ 6.          3.4000001   4.5         1.60000002]
 [ 5.5         2.5         4.          1.29999995]
 [ 6.19999981  2.9000001   4.30000019  1.29999995]
 [ 5.5         4.19999981  1.39999998  0.2       ]
 [ 6.30000019  2.79999995  5.0999999   1.5       ]
 [ 5.5999999   3.          4.0999999   1.29999995]
 [ 6.69999981  2.5         5.80000019  1.79999995]
 [ 7.0999999   3.          5.9000001   2.0999999 ]
 [ 4.30000019  3.          1.10000002  0.1       ]
 [ 5.5999999   2.79999995  4.9000001   2.        ]
 [ 5.5         2.29999995  4.          1.29999995]
 [ 6.          2.20000005  4.          1.        ]
 [ 5.0999999   3.5         1.39999998  0.2       ]
 [ 5.69999981  2.5999999   3.5         1.        ]
 [ 4.80000019  3.4000001   1.89999998  0.2       ]
 [ 5.0999999   3.4000001   1.5         0.2       ]
 [ 5.69999981  2.5         5.  

In [7]:
# Specify features

feature_name = "flower_features"
feature_columns = [tf.feature_column.numeric_column(feature_name, shape=[4])]

In [8]:
classifier = tf.estimator.LinearClassifier(feature_columns=feature_columns,
                                           n_classes=3,
                                           model_dir="/tmp/iris_model"
                                          )

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/tmp/iris_model', '_tf_random_seed': 1, '_save_summary_steps': 100, '_save_checkpoints_secs': 600, '_save_checkpoints_steps': None, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100}


In [15]:
def input_fn(dataset):
    def _fn():
        features = {feature_name: tf.constant(dataset.data)}
        label = tf.constant(dataset.target)
        return features, label
    return _fn
    
print(input_fn(training_set)())

({'flower_features': <tf.Tensor 'Const_3:0' shape=(30, 4) dtype=float32>}, <tf.Tensor 'Const_4:0' shape=(30,) dtype=int64>)


In [16]:
classifier.train(input_fn=input_fn(training_set), steps=1000)

print('FItted')

INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Saving checkpoints for 1 into /tmp/iris_model/model.ckpt.
INFO:tensorflow:loss = 32.9584, step = 1
INFO:tensorflow:global_step/sec: 1996.65
INFO:tensorflow:loss = 9.59655, step = 101 (0.051 sec)
INFO:tensorflow:global_step/sec: 2440.71
INFO:tensorflow:loss = 7.00002, step = 201 (0.041 sec)
INFO:tensorflow:global_step/sec: 2482.59
INFO:tensorflow:loss = 5.7014, step = 301 (0.040 sec)
INFO:tensorflow:global_step/sec: 2539.17
INFO:tensorflow:loss = 4.92116, step = 401 (0.039 sec)
INFO:tensorflow:global_step/sec: 2364.03
INFO:tensorflow:loss = 4.39968, step = 501 (0.042 sec)
INFO:tensorflow:global_step/sec: 2256.25
INFO:tensorflow:loss = 4.02568, step = 601 (0.044 sec)
INFO:tensorflow:global_step/sec: 2342.14
INFO:tensorflow:loss = 3.74363, step = 701 (0.043 sec)
INFO:tensorflow:global_step/sec: 2474.68
INFO:tensorflow:loss = 3.52277, step = 801 (0.041 sec)
INFO:tensorflow:global_step/sec: 2483.78
INFO:tensorflow:loss = 3.34468, s

In [17]:
accuracy = classifier.evaluate(input_fn=input_fn(test_set), steps=100)["accuracy"]

print("Accuracy is {0}".format(accuracy))

INFO:tensorflow:Starting evaluation at 2017-09-09-19:58:33
INFO:tensorflow:Restoring parameters from /tmp/iris_model/model.ckpt-1000
INFO:tensorflow:Evaluation [1/100]
INFO:tensorflow:Evaluation [2/100]
INFO:tensorflow:Evaluation [3/100]
INFO:tensorflow:Evaluation [4/100]
INFO:tensorflow:Evaluation [5/100]
INFO:tensorflow:Evaluation [6/100]
INFO:tensorflow:Evaluation [7/100]
INFO:tensorflow:Evaluation [8/100]
INFO:tensorflow:Evaluation [9/100]
INFO:tensorflow:Evaluation [10/100]
INFO:tensorflow:Evaluation [11/100]
INFO:tensorflow:Evaluation [12/100]
INFO:tensorflow:Evaluation [13/100]
INFO:tensorflow:Evaluation [14/100]
INFO:tensorflow:Evaluation [15/100]
INFO:tensorflow:Evaluation [16/100]
INFO:tensorflow:Evaluation [17/100]
INFO:tensorflow:Evaluation [18/100]
INFO:tensorflow:Evaluation [19/100]
INFO:tensorflow:Evaluation [20/100]
INFO:tensorflow:Evaluation [21/100]
INFO:tensorflow:Evaluation [22/100]
INFO:tensorflow:Evaluation [23/100]
INFO:tensorflow:Evaluation [24/100]
INFO:tensorf